```sql
-- Create Projects table
CREATE TABLE Projects (
    ProjectID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Description VARCHAR2(500),
    StartDate DATE,
    EndDate DATE,
    Status VARCHAR2(50)
);

-- Create Activities table
CREATE TABLE Activities (
    ActivityID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Description VARCHAR2(500),
    StartDate DATE,
    EndDate DATE,
    ProjectID NUMBER NOT NULL,
    CONSTRAINT fk_activities_project FOREIGN KEY (ProjectID)
        REFERENCES Projects(ProjectID)
        ON DELETE CASCADE
);

-- Create Stakeholders table
CREATE TABLE Stakeholders (
    StakeholderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Role VARCHAR2(50),
    ProjectID NUMBER NOT NULL,
    CONSTRAINT fk_stakeholders_project FOREIGN KEY (ProjectID)
        REFERENCES Projects(ProjectID)
        ON DELETE CASCADE
);

-- Create Objectives table
CREATE TABLE Objectives (
    ObjectiveID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Description VARCHAR2(500) NOT NULL,
    ProjectID NUMBER NOT NULL,
    CONSTRAINT fk_objectives_project FOREIGN KEY (ProjectID)
        REFERENCES Projects(ProjectID)
        ON DELETE CASCADE
);

-- Query: List all activities with their associated project details
SELECT 
    a.ActivityID,
    a.Name AS ActivityName,
    a.Description AS ActivityDescription,
    a.StartDate AS ActivityStartDate,
    a.EndDate AS ActivityEndDate,
    p.Name AS ProjectName,
    p.Description AS ProjectDescription
FROM 
    Activities a
JOIN 
    Projects p ON a.ProjectID = p.ProjectID;

-- Query: List all stakeholders and their associated projects
SELECT 
    s.StakeholderID,
    s.Name AS StakeholderName,
    s.Role AS StakeholderRole,
    p.Name AS ProjectName,
    p.Description AS ProjectDescription
FROM 
    Stakeholders s
JOIN 
    Projects p ON s.ProjectID = p.ProjectID;

-- Query: List all objectives with project details
SELECT 
    o.ObjectiveID,
    o.Description AS ObjectiveDescription,
    p.Name AS ProjectName,
    p.Description AS ProjectDescription
FROM 
    Objectives o
JOIN 
    Projects p ON o.ProjectID = p.ProjectID;

-- Query: List activities, stakeholders, and objectives for a specific project
SELECT 
    p.ProjectID,
    p.Name AS ProjectName,
    a.Name AS ActivityName,
    s.Name AS StakeholderName,
    o.Description AS ObjectiveDescription
FROM 
    Projects p
LEFT JOIN 
    Activities a ON p.ProjectID = a.ProjectID
LEFT JOIN 
    Stakeholders s ON p.ProjectID = s.ProjectID
LEFT JOIN 
    Objectives o ON p.ProjectID = o.ProjectID
WHERE 
    p.ProjectID = 1; -- Replace "1" with desired ProjectID

-- Drop tables in correct order to avoid foreign key constraint errors
DROP TABLE Objectives CASCADE CONSTRAINTS;
DROP TABLE Stakeholders CASCADE CONSTRAINTS;
DROP TABLE Activities CASCADE CONSTRAINTS;
DROP TABLE Projects CASCADE CONSTRAINTS;
```

